services:
  - type: web
    name: MyApp
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/MyApp.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
    healthCheckPath: /
    plan: free
